# week08/k8s/product-db.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db-deployment-task10-2d
  labels:
    app: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine # Use the same PostgreSQL image as in Docker Compose
        ports:
        - containerPort: 5432 # Default PostgreSQL port
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-task10-2d # ConfigMap name matches
              key: PRODUCTS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-task10-2d # Secret name matches
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-task10-2d # Secret name matches
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: product-db-service-task10-2d # Internal DNS name for the Product DB
  labels:
    app: product-db
spec:
  selector:
    app: product-db # Selects pods with the label app: product-db
  ports:
    - protocol: TCP
      port: 5432 # The port the service listens on (default PostgreSQL)
      targetPort: 5432 # The port on the Pod (containerPort)
  type: ClusterIP # Only accessible from within the cluster
